-- Reconciliation placeholder for a migration applied directly on staging
-- (project rpepxdgdiqeirdqsazuc) with no local file — the recurring local↔staging
-- drift. The actual schema change is already live on the remote; this empty file
-- only realigns the CLI migration-history check so later migrations can push.
-- See memory: "Migration sync gap".
