-- Baseline indexes migration (non-PK, non-unique)

CREATE INDEX idx_activity_log_action ON activity_log (action);
CREATE INDEX idx_activity_log_composite ON activity_log (mosque_id, created_at DESC);
CREATE INDEX idx_activity_log_created ON activity_log (created_at DESC);
CREATE INDEX idx_activity_log_mosque ON activity_log (mosque_id);
CREATE INDEX idx_ad_subs_active ON ad_subscriptions (mosque_id, status) WHERE (status = 'active');
CREATE INDEX idx_ad_subs_mosque ON ad_subscriptions (mosque_id);
CREATE INDEX idx_aba_mosque ON approved_business_ads (mosque_id);
CREATE INDEX idx_bas_mosque ON business_ads_submissions (mosque_id);
CREATE INDEX idx_bas_status ON business_ads_submissions (mosque_id, status);
CREATE INDEX idx_content_forms_content ON content_forms (content_id);
CREATE INDEX idx_content_items_content_id ON content_items (content_id);
CREATE INDEX idx_content_items_mosque ON content_items (mosque_id);
CREATE INDEX idx_content_items_type ON content_items (mosque_id, type);
CREATE INDEX idx_cns_pending ON content_notification_schedule (mosque_id, is_sent, notification_time) WHERE (is_sent = false);
CREATE INDEX idx_content_notif_mosque ON content_notifications (mosque_id);
CREATE INDEX idx_cta_content ON content_tag_assignments (content_id);
CREATE INDEX idx_cta_tag ON content_tag_assignments (tag_id);
CREATE INDEX idx_content_tags_display ON content_tags (display_category_id);
CREATE INDEX idx_content_tags_mosque ON content_tags (mosque_id);
CREATE INDEX idx_display_categories_mosque ON display_categories (mosque_id);
CREATE INDEX idx_donations_mosque ON donations (mosque_id);
CREATE INDEX idx_jummah_mosque ON jummah (mosque_id);
CREATE INDEX idx_jummah_notif_mosque ON jummah_notifications (mosque_id);
CREATE INDEX idx_lectures_content ON lectures (content_id);
CREATE INDEX idx_lectures_mosque ON lectures (mosque_id);
CREATE INDEX idx_liked_lectures_mosque ON liked_lectures (mosque_id);
CREATE INDEX idx_liked_lectures_user ON liked_lectures (user_id);
CREATE INDEX idx_mhs_latest ON mosque_health_scores (mosque_id, computed_at DESC);
CREATE INDEX idx_mhs_mosque ON mosque_health_scores (mosque_id);
CREATE INDEX idx_mhs_score ON mosque_health_scores (overall_score);
CREATE INDEX idx_mosque_notes_mosque ON mosque_notes (mosque_id);
CREATE INDEX idx_mos_mosque ON mosque_onboarding_steps (mosque_id);
CREATE INDEX idx_mos_status ON mosque_onboarding_steps (mosque_id, status);
CREATE INDEX idx_nd_mosque ON nudge_dismissals (mosque_id);
CREATE INDEX idx_nd_period ON nudge_dismissals (nudge_period);
CREATE INDEX idx_pns_pending ON prayer_notification_schedule (mosque_id, is_sent, notification_time) WHERE (is_sent = false);
CREATE INDEX idx_prayers_mosque ON prayers (mosque_id);
CREATE INDEX idx_projects_mosque ON projects (mosque_id);
CREATE INDEX idx_push_tokens_active ON push_tokens (mosque_id, is_active) WHERE (is_active = true);
CREATE INDEX idx_push_tokens_mosque ON push_tokens (mosque_id);
CREATE INDEX idx_push_tokens_user ON push_tokens (user_id);
CREATE INDEX idx_quran_playlist_mosque ON quran_playlist (mosque_id);
CREATE INDEX idx_rec_log_mosque ON recommendation_log (mosque_id);
CREATE INDEX idx_rec_log_user ON recommendation_log (user_id);
CREATE INDEX idx_saved_content_mosque ON saved_content (mosque_id);
CREATE INDEX idx_saved_content_user ON saved_content (user_id);
CREATE INDEX idx_speaker_data_mosque ON speaker_data (mosque_id);
CREATE INDEX idx_todays_prayers_mosque ON todays_prayers (mosque_id);
CREATE INDEX idx_uci_content ON user_content_interactions (content_id);
CREATE INDEX idx_uci_mosque ON user_content_interactions (mosque_id);
CREATE INDEX idx_uci_user ON user_content_interactions (user_id);
CREATE INDEX idx_user_cart_user ON user_cart (user_id, mosque_id);
CREATE INDEX idx_user_playlist_user ON user_playlist (user_id, mosque_id);
CREATE INDEX idx_user_preferences_mosque ON user_preferences (mosque_id);
